---
title: "Language and the Brain--Scope and History"
output:
  html_document:
    includes:
      in_header: "favicon.html"
    theme: paper
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 2
    #code_folding: hide
---
<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
options(repos = list(CRAN="http://cran.rstudio.com/"))
```

The first two weeks of class we dive into our subject matter by introducing some basic concepts underlying the study of language as manifested in neural processes. 

***

# Introduction

* For the most part, what sets humans apart from other mammals (and really all other animals in general) is the ability to produce and comprehend language--the confluence of a lot of cognitive abilities that may or may not have a centralized control mechanism in the brain. In this class we'll see evidence for the the former, though some people believe the latter!

* Humans **do** language, while other animals do other sorts of communicative systems (like the stuff you learned in LING1000...birdsong, barks, meows, vervet monkey calls, etc.)

* How are we different from those animals that do not have language (as expressed in humans)? Well, we have human brains--brains that are structurally and (we'll see) functionally different from the brains of other animals. This results in our ability to manipulate abstract representations in the service of communicating ideas through some sort of expressive channel (i.e., mouths/ears, hands/eyes).

* OK, then what is it about human brains that allow us to *do* language? Linguists, psychologists, and neuroscientists are interested in this question (though historically Linguists with a capital-L haven't spent too much brain power in this pursuit...we can discuss why).

* We can say a lot about the relationship between language and the brain by observing how we behave given linguistic tasks and whether or not the behaviour is correlated with neural activity. This allows us to generate theories about how specific components of the linguistic system operate and how they might connect to serve Language as a whole. This is ultimately the goal of neurolinguistics.

# Levels of description

* I think the distinction between the *types* of answers to the questions we might ask is an important one. Brennan calls these "levels of description"

| Level of description |Definition|
|--|--|
|Computational | The "problem" meant to be solved by the brain. The sensory input and the interpretation/output|
|Algorithmic| How the brain solves the problem; basically the function that takes input to output|
|Implementational|How the brain (neurons) and the external language-related organs carry out the algorithm|

* Linguists and psychologists work at different levels of description. For example, I study speech perception, which asks how speech sounds are interpreted by humans and assigned to categories based on their experience with language. What level of description would I be working in? I would say it's computational, because I don't deal with fine-grained algorithmic (the math behind the category assignment) or the implementational (what the neural activity may be) that carries out the category assignment. 

# Enterprise of neuro/psycho-linguistics

* So what do we do when we say that we study language and the brain? We do all of these levels od description--but, mostly at the computational level. As linguists we generally don't have the resources available to undertake implementational studies unless we partner with people in other disciplines like psychology or neuroscience.
