---
title: "LING4230syllabus"
output: 
  html_document:
    includes:
      in_header: "favicon.html"
    theme: paper
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

<style type="text/css">
.title {
  display: none;
}

#getting-started img {
  margin-right: 10px;
}

</style>

# **LING 4230: Language and the Brain**\
Instructor: [Chandan Narayan](https://ch-narayan.github.io)\
Office hours: Mondays noon-1 or Wednesdays on Zoom (email to set up appt) [Zoom link](https://yorku.zoom.us/j/97755816919?pwd=L1krNjJlUm9TL2RWWE1HWnZwNXZLQT09)\
A print version of this syllabus is here: [LING4230syllabus](LING4230syllabus.pdf)

## Course Outline and Schedule

***

## Course description:
This course is a seminar surveying various topics in Language and the Brain (or neurolinguistics more broadly). We examine questions like: What are the mental processes that underlie language and what are their behavioral correlates? What brain structures are associated with language? We will read a text book as well as primary research articles, both “classic” and current, that address various problems and issues in linguistic functions and their neurological underpinnings. The course follows the speech chain beginning with basic audition, speech perception and phonological processing, into higher levels of syntactic and semantic processing. The course also addresses research in bi-/multilingualism as well as language disorders, such as aphasia.

## Course prerequisites:
You must have taken LING 2120 (Phonology), LING 2140 (Syntax 1) and LING 3220/PSYC 3290 (Psycholinguistics) with grades of C+ or better; and at least three additional credits in linguistics (AP/LING) at the 3000 level with grades of C+ or better. **I will be checking these prerequisites and you'll be asked to drop the course if you do not have them.**

<!-- ## Learning outcomes: -->

<!-- 1. Demonstrate knowledge of the mechanics and physics of speech production and theories of perception -->
<!-- 2. Demonstrate knowledge of the concepts and methods used in the qualitative analysis of speech sounds -->
<!-- 3. Demonstrate knowledge of speech anatomy -->
<!-- 4. Demonstrate elementary knowledge of speech-language development and disorders -->

## Evaluation

Your grade in the course will be determined by your performance on the following:

* Article questions (4 x 5% each)
* Article presentations (15%)
* Participation (10%)
* Annotated bibliography (25%)
* Final paper (30%)

## Course text and readings
The course follows closely the materials and discussion in:

> Brennan, Jonathan R. (2022) Language and the Brain: A slim guide to neurolinguistics. (Oxford) 

## eClass
All lectures (videos), lecture slides, assignments, discussion boards, online Quizzes and Tests, and assignment submission will happen on the [eClass](http://eclass.yorku.ca) site for the course. Lecture slides will be posted the evening after the lecture happens.


## Class structure
We will go over the day's lecture and discuss issues and problems presented in the chapter for the day. For the most part, the topics discussed each week will follow closely the order of material presented in the textbook, with additional readings discussed in conjunction with the theme of the textbook chapter. It is critical that you do the readings as they will surely illuminate what is discussed in the lecture. Additionally, I ask that you forward me any interesting news stories related to language which you might come across. It is always nice to keep lectures and class content current with the zeitgeist. Stuff like this:

<blockquote class="instagram-media" data-instgrm-permalink="https://www.instagram.com/reel/C-4DwgEhC80/?utm_source=ig_embed&amp;utm_campaign=loading" data-instgrm-version="14" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:540px; min-width:326px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:16px;"> <a href="https://www.instagram.com/reel/C-4DwgEhC80/?utm_source=ig_embed&amp;utm_campaign=loading" style=" background:#FFFFFF; line-height:0; padding:0 0; text-align:center; text-decoration:none; width:100%;" target="_blank"> <div style=" display: flex; flex-direction: row; align-items: center;"> <div style="background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 40px; margin-right: 14px; width: 40px;"></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 100px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 60px;"></div></div></div><div style="padding: 19% 0;"></div> <div style="display:block; height:50px; margin:0 auto 12px; width:50px;"><svg width="50px" height="50px" viewBox="0 0 60 60" version="1.1" xmlns="https://www.w3.org/2000/svg" xmlns:xlink="https://www.w3.org/1999/xlink"><g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd"><g transform="translate(-511.000000, -20.000000)" fill="#000000"><g><path d="M556.869,30.41 C554.814,30.41 553.148,32.076 553.148,34.131 C553.148,36.186 554.814,37.852 556.869,37.852 C558.924,37.852 560.59,36.186 560.59,34.131 C560.59,32.076 558.924,30.41 556.869,30.41 M541,60.657 C535.114,60.657 530.342,55.887 530.342,50 C530.342,44.114 535.114,39.342 541,39.342 C546.887,39.342 551.658,44.114 551.658,50 C551.658,55.887 546.887,60.657 541,60.657 M541,33.886 C532.1,33.886 524.886,41.1 524.886,50 C524.886,58.899 532.1,66.113 541,66.113 C549.9,66.113 557.115,58.899 557.115,50 C557.115,41.1 549.9,33.886 541,33.886 M565.378,62.101 C565.244,65.022 564.756,66.606 564.346,67.663 C563.803,69.06 563.154,70.057 562.106,71.106 C561.058,72.155 560.06,72.803 558.662,73.347 C557.607,73.757 556.021,74.244 553.102,74.378 C549.944,74.521 548.997,74.552 541,74.552 C533.003,74.552 532.056,74.521 528.898,74.378 C525.979,74.244 524.393,73.757 523.338,73.347 C521.94,72.803 520.942,72.155 519.894,71.106 C518.846,70.057 518.197,69.06 517.654,67.663 C517.244,66.606 516.755,65.022 516.623,62.101 C516.479,58.943 516.448,57.996 516.448,50 C516.448,42.003 516.479,41.056 516.623,37.899 C516.755,34.978 517.244,33.391 517.654,32.338 C518.197,30.938 518.846,29.942 519.894,28.894 C520.942,27.846 521.94,27.196 523.338,26.654 C524.393,26.244 525.979,25.756 528.898,25.623 C532.057,25.479 533.004,25.448 541,25.448 C548.997,25.448 549.943,25.479 553.102,25.623 C556.021,25.756 557.607,26.244 558.662,26.654 C560.06,27.196 561.058,27.846 562.106,28.894 C563.154,29.942 563.803,30.938 564.346,32.338 C564.756,33.391 565.244,34.978 565.378,37.899 C565.522,41.056 565.552,42.003 565.552,50 C565.552,57.996 565.522,58.943 565.378,62.101 M570.82,37.631 C570.674,34.438 570.167,32.258 569.425,30.349 C568.659,28.377 567.633,26.702 565.965,25.035 C564.297,23.368 562.623,22.342 560.652,21.575 C558.743,20.834 556.562,20.326 553.369,20.18 C550.169,20.033 549.148,20 541,20 C532.853,20 531.831,20.033 528.631,20.18 C525.438,20.326 523.257,20.834 521.349,21.575 C519.376,22.342 517.703,23.368 516.035,25.035 C514.368,26.702 513.342,28.377 512.574,30.349 C511.834,32.258 511.326,34.438 511.181,37.631 C511.035,40.831 511,41.851 511,50 C511,58.147 511.035,59.17 511.181,62.369 C511.326,65.562 511.834,67.743 512.574,69.651 C513.342,71.625 514.368,73.296 516.035,74.965 C517.703,76.634 519.376,77.658 521.349,78.425 C523.257,79.167 525.438,79.673 528.631,79.82 C531.831,79.965 532.853,80.001 541,80.001 C549.148,80.001 550.169,79.965 553.369,79.82 C556.562,79.673 558.743,79.167 560.652,78.425 C562.623,77.658 564.297,76.634 565.965,74.965 C567.633,73.296 568.659,71.625 569.425,69.651 C570.167,67.743 570.674,65.562 570.82,62.369 C570.966,59.17 571,58.147 571,50 C571,41.851 570.966,40.831 570.82,37.631"></path></g></g></g></svg></div><div style="padding-top: 8px;"> <div style=" color:#3897f0; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:550; line-height:18px;">View this post on Instagram</div></div><div style="padding: 12.5% 0;"></div> <div style="display: flex; flex-direction: row; margin-bottom: 14px; align-items: center;"><div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(0px) translateY(7px);"></div> <div style="background-color: #F4F4F4; height: 12.5px; transform: rotate(-45deg) translateX(3px) translateY(1px); width: 12.5px; flex-grow: 0; margin-right: 14px; margin-left: 2px;"></div> <div style="background-color: #F4F4F4; border-radius: 50%; height: 12.5px; width: 12.5px; transform: translateX(9px) translateY(-18px);"></div></div><div style="margin-left: 8px;"> <div style=" background-color: #F4F4F4; border-radius: 50%; flex-grow: 0; height: 20px; width: 20px;"></div> <div style=" width: 0; height: 0; border-top: 2px solid transparent; border-left: 6px solid #f4f4f4; border-bottom: 2px solid transparent; transform: translateX(16px) translateY(-4px) rotate(30deg)"></div></div><div style="margin-left: auto;"> <div style=" width: 0px; border-top: 8px solid #F4F4F4; border-right: 8px solid transparent; transform: translateY(16px);"></div> <div style=" background-color: #F4F4F4; flex-grow: 0; height: 12px; width: 16px; transform: translateY(-4px);"></div> <div style=" width: 0; height: 0; border-top: 8px solid #F4F4F4; border-left: 8px solid transparent; transform: translateY(-4px) translateX(8px);"></div></div></div> <div style="display: flex; flex-direction: column; flex-grow: 1; justify-content: center; margin-bottom: 24px;"> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; margin-bottom: 6px; width: 224px;"></div> <div style=" background-color: #F4F4F4; border-radius: 4px; flex-grow: 0; height: 14px; width: 144px;"></div></div></a><p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;"><a href="https://www.instagram.com/reel/C-4DwgEhC80/?utm_source=ig_embed&amp;utm_campaign=loading" style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">A post shared by 60 Minutes Australia (@60minutes9)</a></p></div></blockquote>
<script async src="//www.instagram.com/embed.js"></script>


1) I will present for about an hour during each meeting. The materials I will present will come directly from the textbook, with some supplemental materials added

2) After my presentation there will be two to three student presentations of primary research articles associated with each chapter. For example, if the chapter is about word structure representation in the brain, we will read a few articles directly reporting results of experiments dealing with word structure. **These articles will then be presented by students.** Each student will be responsible for one presentation of an article during the term. The presentation should be roughly 10-12 minutes long and MUST INCLUDE: the **question** the article is addressing, the **method** the researchers use to answer the question, the **results** of the experiment, and the author's **interpretation** of the results. The presentation must conclude with at least two discussion questions you might have about the article. The articles themselves will be linked below. Students will be randomly assigned to a particular article. 

#### Article questions

Students are responsible for submitting **four** (4) sets of questions for articles we read during the term. Any four articles can be chosen by the student. Students should offer at least 2 (though more questions the better for your mark) questions about the article. The questions should be informed and thoughtful. **Do not give me questions like "What about bilinguals?"** or questions that are extremely broad and scope. They can be questions about methodology, previous research, interpretation of the data or the conclusions drawn.

Questions must be submitted in **hard copy** on the day when we are discussing the particular article at the beginning of class. For example, if you choose to provide questions for a paper in week 5, submit them at the start of week 5's class. Questions must be typed or **neatly** handwritten and must include your name, the question set (i.e., "Set #2" if it's the second set of questions you're submitting), and the article name and author in the heading. Each set of questions if worth 5% of your grade. If you submit competent questions (and you do everything I ask regarding labelling the question set, etc.) then you can expect to get full marks on the assignment. That is, I'm not grading the quality of your questions per se.

**You must have submitted questions for two (2) articles by October 28th's class.**

#### Structure of journal article presentations

As explained above, student's are responsible for one article presentation during the term. The presentation should last around 20 minutes, which means it shouldn't exceed 20 slides. Ideally you will use [slides.google.com](slides.google.com) to compose your presentation so that we can access it seamlessly in class. When you save your file, besure to do so in the following manner: "YOUR_LAST_NAME-ARTICLE_AUTHOR_NAME_Fall2024". The general structure of the presentation should be:

* Introduce the problem/question asked by the article
* Provide some background on what the article says has already been done regarding this topic
* Briefly explain the methodology used in the experiment
* Explain the results of the experiment(s), using visuals like graphs and plots, along with your own explanations
* What does this mean for the original question being asked?
* Any questions you might have about the research

Here are some sample presentations. Good ones ([this](docs/Hicock.pdf), [this](docs/LING 4320 miglietta 2013.pdf)). Too much text on the slides in [this](LING 4230 - presentation slides.pdf) and [this.](docs/article_20.pdf)

#### Annotated bibliography and Final paper

The final paper consists of two pieces of work: an annotated bibliography and the paper itself. Students, **in consultation with the me** (please talk with me about your ideas a few weeks into the course), will come up with a paper topic. The paper can be either 1) A state-of-the-art report on a particular topic, or 2) a faux experimental paper that addresses a particular question in-line with the readings done in class. The paper should clearly articulate the history of the particular line of thinking and approach to the topic. Sample topics include: The genetic basis for speech (FOXP2); Cochlear implantation and language processing; Neural correlates of categorical perception; etc. Some sample papers will be posted on line.

**The Annotated bibliography is due, via eClass portal anytime during Week 12**
**The final paper is due by December 11.**

### Email policy
If you cannot attend the scheduled office hour, contact me to arrange another time. I will do my best to answer your phone and email messages promptly. I do not, generally, answer email on the weekend. Please email me from your yorku.ca account and put ‘LING 4230’ in the subject line. Emails sent from non-York accounts will be ignored. Please sign your emails; I will not reply to anonymous messages. My response to your email may be brief and may not come within 48 hours. **Please be patient**.

## Grading
York University uses a grading system detailed [here](http://calendars.registrar.yorku.ca/2012-2013/academic/grades/). Please familiarize yourself with it. 

## Academic Honesty and Integrity
York students are required to maintain high standards of academic integrity and are subject to the Senate Policy on Academic Honesty. Please review the documents available [here](https://www.yorku.ca/secretariat/policies/policies/academic-honesty-senate-policy-on/). Academic offences are treated very seriously, and the disciplinary procedures are described there as well. Please consult the code if you have any question about the nature of academic offences and their penalties.

## Course Withdrawal (W) option
In the period between the last day to drop a course without receiving a grade and the final day of classes in a term, undergraduate students are permitted to withdraw from a course with the condition that the course enrolment remains on a student’s transcript, denoted by a “W” in the University’s records and on the student’s transcript as the grade decision. No credit value will be retained for the course and no value will be included in the calculation of a student's grade point average (GPA). Please go [here](https://myacademicrecord.students.yorku.ca/course-withdrawal) for details.

## Schedule

| Week | Date |  Topic                  | Chapter    | Articles     |
|------|------|-------------------------|---------|--------------|
| 1    | 9/09 | Intro:Scope and History | Ch.1    |              |
| 2    | 9/16 | Brain structures       | Ch.2     | -            |
| 3    | 9/23 | Sounds 1                | Ch.3    | [Kubanek et al.(2013)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0053398); [Mesgarani et al. (2014)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4350233/)|
| 4    | 9/30 | Sounds 2                | Ch.3    | [Saoud et al. (2012)](https://www.jneurosci.org/content/jneuro/32/1/275.full.pdf); [van Wassenhove et al. (2007)](https://www.utdallas.edu/~assmann/hcs6367/van_wassenhove_grant_poeppel07.pdf); [Sohoglu et al.(2012)](https://www.jneurosci.org/content/jneuro/32/25/8443.full.pdf)             |
| 5    | 10/7 | Phonemes 1                        | Ch.4     |[Scharinger et al. (2011)](https://www.researchgate.net/profile/William-Idsardi/publication/51123294_A_Comprehensive_Three-dimensional_Cortical_Map_of_Vowel_Space/links/565232c708ae4988a7aef7ca/A-Comprehensive-Three-dimensional-Cortical-Map-of-Vowel-Space.pdf); [Arsenault and Buchsbaum (2015)](https://www.jneurosci.org/content/jneuro/35/2/634.full.pdf);[Virtala et al. (2023)](https://www.sciencedirect.com/science/article/pii/S0278262623000313/pdfft?md5=931540977f2e3a1b9cfa15d66ec0dd87&pid=1-s2.0-S0278262623000313-main.pdf)             |
|     | 10/14| READING WEEK                            | ---    |   |
| 6    |10/21 | Phonemes 2                          | Ch.4    |[Maffei et al.(2017)](https://www-sciencedirect-com.ezproxy.library.yorku.ca/science/article/pii/S0010945217303404); [Möttönen and Watkins (2009)](https://www.jneurosci.org/content/jneuro/29/31/9819.full.pdf); [Jochaut et al. (2015)](https://www.frontiersin.org/articles/10.3389/fnhum.2015.00171/full)             |
| 7    |10/28 | Words                          | Ch.5    | [Davis and Johnsrude (2003)](https://www.jneurosci.org/content/jneuro/23/8/3423.full.pdf);[Marinkovic et al.(2003)](https://www.cell.com/neuron/pdf/S0896-6273(03)00197-1.pdf);[MacGregor et al. (2012)](https://www.nature.com/articles/ncomms1715)             |
| 8    |11/4  | Semantics                 | Ch.6    |[Huth and Gallant (2016)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4852309/);[Pobric et al. (2007)](https://www.pnas.org/doi/full/10.1073/pnas.0707383104); [Pulvermüller et al.(2005)](https://sci-hub.se/10.1111/j.1460-9568.2005.03900.x)            |
|9    |11/11 | Prediction 1              | Ch.7    | [Federmeier and Kutas (1999)](https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=8aec17d667f5b58fe2d9473a94553b13c6fd63a7); [van Berkum et al.(2003)](https://pure.mpg.de/rest/items/item_59347/component/file_59348/content) |
|10    |11/18 | Prediction 2              | Ch.7    | [Gouvea et al. (2010)](https://www.researchgate.net/profile/Colin-Phillips-3/publication/228641799_The_linguistic_processes_underlying_the_P600/links/0912f5097c882409cc000000/The-linguistic-processes-underlying-the-P600.pdf);[Klimovich-Gray et al. (2019)](https://www.jneurosci.org/content/jneuro/39/3/519.full.pdf) |
|11    |11/25 | Sentences 1              | Ch.8    |[Pallier et al.(2011)](https://www.pnas.org/doi/full/10.1073/pnas.1018711108);[Bemis and Pylkkänen (2011)](https://www.jneurosci.org/content/jneuro/31/8/2801.full.pdf);[Frankland and Greene (2015)](https://www.pnas.org/doi/full/10.1073/pnas.1421236112)  |
|12    |12/2  | Sentences 2              | Ch.8    | [Matchin et al.(2014)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4252493/);[Amici et al.(2007)](https://www.jneurosci.org/content/jneuro/27/23/6282.full.pdf) |



