---
title: "Practice problems and MT review"
output:
  html_document:
    includes:
      in_header: "favicon.html"
    theme: paper
    toc: true
    toc_float: true
    collapsed: false
    number_sections: false
    toc_depth: 3
    #code_folding: hide
---
<style type="text/css">
  body{
  font-size: 12pt;
}
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# MT 

The midterm will cover all of the materials from Lectures 1-7. Although the materials you'll be tested on come from the lecture notes and not strictly the textbook, if you do have the textbook, it might be useful for you to review the lecture topics in order to get any additional clarity on topics. 

The midterm will have 20 questions and be a combination of multiple choice/true-false (11) and short answer problems (9). **This is a closed book test, but you may have a calculator.** You'll have the entire class time to complete the test. 

Here are the concepts that will be important for you to review:

- Tube resonances (quarter- and half-wave tubes)
- Absolute intensity to dB calculation
- The pressure dynamics of respiration (i.e., why/how lungs expand and how it's affected by changes in pressure)
- Complex periodic waves and how to read its spectrum representation
- The various forces acting on air molecules that have been excited from equilibrium position resulting in sound
- The relationship between frequency and period of a periodic wave
- How to add two sine waves (similar to the quiz)
- How to determine the frequency and harmonics of a complex periodic wave from the time x amplitude waveform representation
- Boyle's law
- The relationship between frequency and wavelength
- RMS amplitude
- Laryngeal anatomy (the major bone and cartilages and their functions and location)

# Practice problems

Work on the below problems then watch this [video](https://yorku.zoom.us/rec/play/DuI-RwvEamQkIqecRzGalgjLZmX67BIVTgwJV8zzBzqcmNX88_2WvV208qlyRok4P78VLu29tJMtEhx7.zFfHKNJLvu_ugbio?continueMode=true), which has the solutions I've worked out.

## Pressure and volume

1. A 5L container has a gas that exerts a pressure of 25Pa. I built a "doubling" machine that increases the volume of the container to 25L. What is the new pressure of the gas?

## Frequency, period, wavelength

*Use 331m/s as the speed of sound in air*

2. What is the wavelength of a pure tone with a frequency of 3kHz?
3. What is the period (in ms) of a tone with a wavelength of 600cm?

## Intensity to dB

4. Suppose a sound has an intensity of 5.5 x $10^{-5}$ $W/m^2$. How loud is this sound in decibels?
5. If a sound has an intensity of 0.04 $W/m^2$, what is its value in decibels?
6. What is the absolute intensity in $W/m^2$ of a sound that is 60dB?

## Tube resonances

*Use 331m/s as the speed of sound in air*

7. What is the 4th resonance of an open-open tube that's 1m long?
8. How long is an open-closed tube that has an $F_2$ of 1500Hz?
